import type { Metadata } from "next";
import { sportingGrotesque } from "@/fonts/sporting-grotesque";
import "@/styles/globals.css";
import { Footer, Header } from "@/components/layout";

export const metadata: Metadata = {
  title: "Raintor.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sportingGrotesque.variable} antialiased text-lg leading-8`}
      >
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-1 shrink-0 mt-20">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
