import type { Metadata } from "next";
import { sportingGrotesque } from "@/fonts/sporting-grotesque";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Raintor.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sportingGrotesque.variable} antialiased text-lg leading-8`}
      >
        {children}
      </body>
    </html>
  );
}
