import type { Metadata } from "next";
import { sportingGrotesque } from "@/fonts/sporting-grotesque";
import "@/styles/globals.css";
import { Footer, Header } from "@/components/layout";

export const metadata: Metadata = {
  title: "Raintor.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sportingGrotesque.variable} antialiased text-lg leading-8`}
      >
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
